export default PATH = {
  SPLASH: 'SPLASH',
  LANDING: 'LANDING',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  HOME: 'HOME',
  BUILDING_DETAIL: 'BUILDING_DETAIL',
  TRANSACTIONS_HISTORY: 'TRANSACTIONS_HISTORY',
}
